### ISSUE TITLE
When I change locale some page not found

### ISSUE THREAD

**Issue by joker8x** [totaljs/eshop#22]
Hi! Thank you for great app. I trying translate app to my language. When I change locale by this code
`F.onLocale = function  (req) {
	return "vi";
}`

But when I try access to homepage, privacy, contact those will be not found. I can only access to shop, blogs, account.

I used example database.

**Comment by petersirka** [comment]
Hi @joker8x,
just rename `your.resource` to `default.resource`. Thank you!

**Comment by joker8x** [comment]
Hi @petersirka. Thank you for your help, I fixed it by change language of page
