### ISSUE TITLE
After Instalation. 

### ISSUE THREAD

**Issue by neoartdoo** [totaljs/eshop#27]
So I installed, i wont to test it and decide. affter installation runing with some litle bugs.  
Here is a console.log 

` ### D:\node\home\eshop-master>npm install
Eshop@8.0.0 D:\node\home\eshop-master
+-- paypal-express-checkout@1.6.0
-- total.js@2.4.0

npm WARN Eshop@8.0.0 No repository field.

D:\node\home\eshop-master>node debug.js
---------------------------------> PID: 5952 (v8.0)
====================================================
PID         : 5884
Node.js     : v6.9.5
Total.js    : v2.4.0
OS          : win32 6.1.7601
====================================================
Name        : E-shop
Version     : 8.0.0
Author      : Peter Širka
Date        : 2017-02-08 21:12:09
Mode        : debug
====================================================

http://127.0.0.1:8000/

======= 2017-02-08 21:12:41: Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-1611262318Tufbw9.jpg +profile "*" -filt
er "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\node\home\eshop-master\tmp\images
-small-1611262318Tufbw9.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.
 (http://127.0.0.1:8000/images/small/1611262318Tufbw9.jpg) Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-161126231
8Tufbw9.jpg +profile "*" -filter "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\nod
e\home\eshop-master\tmp\images-small-1611262318Tufbw9.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
======= 2017-02-08 21:12:41: Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-1611262202Tkvs19.jpg +profile "*" -filt
er "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\node\home\eshop-master\tmp\images
-small-1611262202Tkvs19.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.
 (http://127.0.0.1:8000/images/small/1611262202Tkvs19.jpg) Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-161126220
2Tkvs19.jpg +profile "*" -filter "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\nod
e\home\eshop-master\tmp\images-small-1611262202Tkvs19.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
======= 2017-02-08 21:12:41: Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-1611262232T4433i.jpg +profile "*" -filt
er "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\node\home\eshop-master\tmp\images
-small-1611262232T4433i.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.
 (http://127.0.0.1:8000/images/small/1611262232T4433i.jpg) Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-161126223
2T4433i.jpg +profile "*" -filter "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\nod
e\home\eshop-master\tmp\images-small-1611262232T4433i.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
======= 2017-02-08 21:12:41: Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-1611262223Tpu112.jpg +profile "*" -filt
er "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\node\home\eshop-master\tmp\images
-small-1611262223Tpu112.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.
 (http://127.0.0.1:8000/images/small/1611262223Tpu112.jpg) Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-161126222
3Tpu112.jpg +profile "*" -filter "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\nod
e\home\eshop-master\tmp\images-small-1611262223Tpu112.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
======= 2017-02-08 21:12:42: Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-1611262252Tzj817.jpg +profile "*" -filt
er "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\node\home\eshop-master\tmp\images
-small-1611262252Tzj817.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.
 (http://127.0.0.1:8000/images/small/1611262252Tzj817.jpg) Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-161126225
2Tzj817.jpg +profile "*" -filter "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\nod
e\home\eshop-master\tmp\images-small-1611262252Tzj817.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
======= 2017-02-08 21:12:42: Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-1611262300Tonf16.jpg +profile "*" -filt
er "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\node\home\eshop-master\tmp\images
-small-1611262300Tonf16.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.
 (http://127.0.0.1:8000/images/small/1611262300Tonf16.jpg) Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-161126230
0Tonf16.jpg +profile "*" -filter "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\nod
e\home\eshop-master\tmp\images-small-1611262300Tonf16.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
======= 2017-02-08 21:12:42: Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-1611262242T1d7q6.jpg +profile "*" -filt
er "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\node\home\eshop-master\tmp\images
-small-1611262242T1d7q6.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.
 (http://127.0.0.1:8000/images/small/1611262242T1d7q6.jpg) Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-161126224
2T1d7q6.jpg +profile "*" -filter "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\nod
e\home\eshop-master\tmp\images-small-1611262242T1d7q6.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
======= 2017-02-08 21:12:42: Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-1611262325Tu4tke.jpg +profile "*" -filt
er "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\node\home\eshop-master\tmp\images
-small-1611262325Tu4tke.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.
 (http://127.0.0.1:8000/images/small/1611262325Tu4tke.jpg) Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-161126232
5Tu4tke.jpg +profile "*" -filter "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\nod
e\home\eshop-master\tmp\images-small-1611262325Tu4tke.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
======= 2017-02-08 21:12:43: Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-1611270911Tm8m2j.jpg +profile "*" -filt
er "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\node\home\eshop-master\tmp\images
-small-1611270911Tm8m2j.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.
 (http://127.0.0.1:8000/images/small/1611270911Tm8m2j.jpg) Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-161127091
1Tm8m2j.jpg +profile "*" -filter "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\nod
e\home\eshop-master\tmp\images-small-1611270911Tm8m2j.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
======= 2017-02-08 21:12:43: Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-1611262359Ta2v65.jpg +profile "*" -filt
er "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\node\home\eshop-master\tmp\images
-small-1611262359Ta2v65.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.
 (http://127.0.0.1:8000/images/small/1611262359Ta2v65.jpg) Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-161126235
9Ta2v65.jpg +profile "*" -filter "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\nod
e\home\eshop-master\tmp\images-small-1611262359Ta2v65.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
======= 2017-02-08 21:12:43: Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-1611262313T8tbyl.jpg +profile "*" -filt
er "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\node\home\eshop-master\tmp\images
-small-1611262313T8tbyl.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.
 (http://127.0.0.1:8000/images/small/1611262313T8tbyl.jpg) Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-161126231
3T8tbyl.jpg +profile "*" -filter "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\nod
e\home\eshop-master\tmp\images-small-1611262313T8tbyl.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
======= 2017-02-08 21:12:43: Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-1611270001Tb1gpe.jpg +profile "*" -filt
er "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\node\home\eshop-master\tmp\images
-small-1611270001Tb1gpe.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.
 (http://127.0.0.1:8000/images/small/1611270001Tb1gpe.jpg) Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-161127000
1Tb1gpe.jpg +profile "*" -filter "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\nod
e\home\eshop-master\tmp\images-small-1611270001Tb1gpe.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
======= 2017-02-08 21:13:08: Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-1611271007Twyhfp.jpg +profile "*" -filt
er "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\node\home\eshop-master\tmp\images
-small-1611271007Twyhfp.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.
 (http://127.0.0.1:8000/images/small/1611271007Twyhfp.jpg) Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-small-161127100
7Twyhfp.jpg +profile "*" -filter "Box" -thumbnail "200x150" -background "white" -extent 0x0 -gravity "Center" -extent "200x150" -quality 90 D:\nod
e\home\eshop-master\tmp\images-small-1611271007Twyhfp.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
======= 2017-02-08 21:13:11: Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-large-1611270001Tjn3uv.jpg +profile "*" -filt
er "Box" -thumbnail "500x300" -background "white" -extent 0x0 -gravity "Center" -extent "500x300" -quality 90 D:\node\home\eshop-master\tmp\images
-large-1611270001Tjn3uv.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.
 (http://127.0.0.1:8000/images/large/1611270001Tjn3uv.jpg) Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-large-161127000
1Tjn3uv.jpg +profile "*" -filter "Box" -thumbnail "500x300" -background "white" -extent 0x0 -gravity "Center" -extent "500x300" -quality 90 D:\nod
e\home\eshop-master\tmp\images-large-1611270001Tjn3uv.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
======= 2017-02-08 21:13:11: Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-large-1611270001Tb1gpe.jpg +profile "*" -filt
er "Box" -thumbnail "500x300" -background "white" -extent 0x0 -gravity "Center" -extent "500x300" -quality 90 D:\node\home\eshop-master\tmp\images
-large-1611270001Tb1gpe.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.
 (http://127.0.0.1:8000/images/large/1611270001Tb1gpe.jpg) Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-large-161127000
1Tb1gpe.jpg +profile "*" -filter "Box" -thumbnail "500x300" -background "white" -extent 0x0 -gravity "Center" -extent "500x300" -quality 90 D:\nod
e\home\eshop-master\tmp\images-large-1611270001Tb1gpe.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
======= 2017-02-08 21:13:12: Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-large-1611270001Ttcy13.jpg +profile "*" -filt
er "Box" -thumbnail "500x300" -background "white" -extent 0x0 -gravity "Center" -extent "500x300" -quality 90 D:\node\home\eshop-master\tmp\images
-large-1611270001Ttcy13.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.
 (http://127.0.0.1:8000/images/large/1611270001Ttcy13.jpg) Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-large-161127000
1Ttcy13.jpg +profile "*" -filter "Box" -thumbnail "500x300" -background "white" -extent 0x0 -gravity "Center" -extent "500x300" -quality 90 D:\nod
e\home\eshop-master\tmp\images-large-1611270001Ttcy13.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
======= 2017-02-08 21:13:12: Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-large-1611270001T1ap91.jpg +profile "*" -filt
er "Box" -thumbnail "500x300" -background "white" -extent 0x0 -gravity "Center" -extent "500x300" -quality 90 D:\node\home\eshop-master\tmp\images
-large-1611270001T1ap91.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.
 (http://127.0.0.1:8000/images/large/1611270001T1ap91.jpg) Error: Command failed: gm -convert D:\node\home\eshop-master\tmp\images-large-161127000
1T1ap91.jpg +profile "*" -filter "Box" -thumbnail "500x300" -background "white" -extent 0x0 -gravity "Center" -extent "500x300" -quality 90 D:\nod
e\home\eshop-master\tmp\images-large-1611270001T1ap91.jpg
'gm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

`

**Comment by petersirka** [comment]
Hi @neoartdoo, you have to install [GraphicsMagick](http://www.graphicsmagick.org/) on your system and everything will work correctly.

<https://docs.totaljs.com/eshop-cms/latest.html#pages~Welcome>
Thank you!
