### ISSUE TITLE
Unique Product URL Conflict

### ISSUE THREAD

**Issue by dinkco** [totaljs/eshop#28]
If two different products contain the same string, e.g. "My Cool Product", it will generate same URL for both products such as:
`http://localhost:8000/product/my-cool-product/`

I think we should add a integer (or hashid) at the end uf URL after checking if same string already exists to avoid this conflict. Or something like that. Unfortunately, I don't know how to do this and it just caught my attention after playing around with it.

**Comment by petersirka** [comment]
I forgot on it. Yes, there isn't any URL validator. I assume that the eshop won't contain double named products.

**Comment by dinkco** [comment]
It's quite possible there will be products with the same title but different description and other attributes, especially when you have lot of items in the shop. Keeping an eye on all previous titles will soon become impossible to manage in a medium to large store. 

Thanks for looking into it.

**Comment by petersirka** [comment]
@dinkco this is a small solution, isn't optimized for many products... I have created a lot of eshops and none of them didn't have products with same names. It's bad for SEO and for employees too.

But I agree that there should be some validator for it.
