### ISSUE TITLE
Multi-select Product

### ISSUE THREAD

**Issue by Nayar** [totaljs/eshop#30]
On this page

![screen shot 2017-03-05 at 1 19 19 pm](https://cloud.githubusercontent.com/assets/454815/23586033/738d8782-01a6-11e7-9d3f-c63d446ddf7d.png)

Would be great if we could select multiple products and mass delete

**Comment by petersirka** [comment]
Hi @Nayar,
multi-select with another features will be in premium eshop version coming soon.

Thank you!
