### ISSUE TITLE
Order-status email not sending

### ISSUE THREAD

**Issue by g666nz** [totaljs/eshop#32]
Hi, 
so i was trying to respond to a client but would recieve empty email. I found the problem was due to this little code in the order-status.html 

<div style="margin-bottom:10px;line-height:18px;border-bottom:1px solid #F0F0F0;padding-bottom:5px">
	<div style="font-weight:bold;text-transform:uppercase;color:black">@(Created)</div>
	<div>@{model.datecreated.format('@(yyyy-MM-dd)')}</div>
</div>
Debug said format was not recognised or something on those lines.
Is there any solution around this. Apart from just removing that code.

I am using total.js v2.4.0

**Comment by petersirka** [comment]
Hi @g666nz,
thank you. I have fixed it.

**Comment by g666nz** [comment]
Hi, 
can you tell me what you updated so i can add it to my code. 
Thank you

**Comment by molda** [comment]
See this commit https://github.com/totaljs/eshop/commit/b8e4142cb64af23e50e70a34351ea0b48d6e7aa2
