### ISSUE TITLE
Sign up account not saving

### ISSUE THREAD

**Issue by g666nz** [totaljs/eshop#33]
User sign up is not working, the google sign up is working. I receive a notification regarding the user signing up, however it not adding them onto the user list and they are not being able to sign up it says user not found.

**Comment by g666nz** [comment]
I'm also getting no debug info. It seems to just not be getting stored into the nosql database.

**Comment by petersirka** [comment]
Shit, my mistake. Please download the source-code again.
1000x thank you.

**Comment by g666nz** [comment]
No problem. Having fun playing around with total.js, so you will be getting bothered by me here and there.

**Comment by g666nz** [comment]
Hi peter,
My site has been online for almost a week and a half now, vedicseeds.in and i can't shut my website down, i've had to customise it to suit indian needs. Can you just send me the commit to see what changes need to be made so I don't have to start the entire project from scratch. 
Thank you

**Comment by petersirka** [comment]
@g666nz please write on [Total.js Messenger](https://messeger.totaljs.com).

**Comment by g666nz** [comment]
I'm getting a 502 error bad gateway message while trying to open the site.

**Comment by petersirka** [comment]
Sorry, bad link:
https://messenger.totaljs.com
