### ISSUE TITLE
Problem with Changing theme w.r.t ADD TO CART function

### ISSUE THREAD

**Issue by g666nz** [totaljs/eshop#35]
I am changing the template of the eshop. And I am currently having problems adding products to the cart. When i click the add to cart button, it successfully calls the $('.details-buy').on(click... function in the default.js file, however it fails to execute the FIND("checkout"). I've added little snippets of the code below. Any help would be appreciated.

<div class="detail-checkout">
                <div>@(The product <b>@{model.name}</b> is in your shopping cart) <b class="data-checkout-count"></b>.</div>
                <span class="fa fa-shopping-cart"></span><a href="/checkout/" class="b">@(Order it now)</a>
              </div>
              <ul class="list-unstyled">
                <li>
                  <button data-id="@{model.id}" data-price="@{model.price}" class="btn btn-important btn-lg detail-buy">
                    <span class="btn-text">Add to cart</span>
                    -
                    <span class="product-price"><b>@{currency(model.price)}</b>@{if model.priceold > model.price} <span class="red">@{currency(model.priceold)}</span>@{fi}</span>
                  </button>

That's above code is for Adding the cart but during the process i get this error on the browser console.

Uncaught TypeError: Cannot read property 'append' of undefined
    at HTMLButtonElement.<anonymous> (default.js:29)
    at HTMLButtonElement.dispatch (jquery-3.1.1.min.js:3)
    at HTMLButtonElement.q.handle (jquery-3.1.1.min.js:3)

It's unable to get any data from FIND('checkout') function. 

var buy = $('.detail-buy').on('click', function() {
		alert("something happening");
		var el = $(this);
		var price = parseFloat(el.attr('data-price'));
		var id = el.attr('data-id');
		//alert(price+" ,"+id);
		var checkout = FIND('checkout');	
		checkout.append(id, price, 1);

**Comment by petersirka** [comment]
Here is defined jComponent `checkout`:
https://github.com/totaljs/eshop/blob/master/themes/default/views/layout.html#L46

Premium Eshop has better implementation of Shopping Cart.

**Comment by g666nz** [comment]
You sir are a god send. As always thank you. I shall give a look into purchasing total.js premium. And once again thank you.
