### ISSUE TITLE
Category issue

### ISSUE THREAD

**Issue by DimaJedi** [totaljs/eshop#37]
Translated shop with localization guide in Russian. 
When create or rename categories to russian language in CMS, it either becomes not selectable or transforms in empty part of url and doesn't work.

In this case category 'Колонки' transformed in 'n' in url
![screen shot 2017-07-05 at 3 26 11 pm](https://user-images.githubusercontent.com/14922318/27864224-58ef4a32-6196-11e7-8a92-df2f9d2e858e.png)

**Comment by petersirka** [comment]
Hi @DimaJedi,
I know where is the problem. Please follow these steps for your localization:

- install slug from NPM `$ npm install slug`
- create a definition file called `overrides.js`

```javascript
const slug = require('slug');
const slug_options = { lower: true };

String.prototype.slug = function(max) {
    !max && (max = 60);
    var output = slug(this, slug_options);
    return (output.length > max ? output.substring(0, max) : output);
};
```

I'll write a blog about this.
Give me a feedback.

Thank you!

**Comment by DimaJedi** [comment]
Hello @petersirka!
Works extremely fine now!
Thanks a lot.

**Comment by kasraJannati** [comment]
Hello @DimaJedi  !
How could you transform "Колонки" into "n" ?
I created a definition file called overrides.js but my url is empty and doesn't work yet :-(

**Comment by Di9** [comment]
@kasraJannati you need at least to rename your page/category or better create again to apply the changes :)
p.s. and I hope you sure made a restart of the app...
