### ISSUE TITLE
what is page() function?

### ISSUE THREAD

**Issue by Wataru811** [totaljs/eshop#42]
hello,  I have a question about following code, from EShop premium.

I could not find the details of function ' self.page()' from documents.
what is the definition of this function 'page()' 5 variables meaning?  or where is the source code path for this function?　

```
// Homepage
function view_homepage() {
	var self = this;
	// Increases the performance (1 minute cache)
	self.memorize('cache.homepage', '1 minute', DEBUG, function() {
		var options = {};
		options.max = 12;
		options.sort = '3';
		options.published = true;
		$QUERY('Product', options, (err, response) => self.page('/', 'index', response, false, true));
	});
}
```

**Comment by petersirka** [comment]
Hi @Wataru811,

```javascript
Controller.prototype.page = function(url, callback, view, model, cache, partial) {
    // code
};

$QUERY('Product', options, (err, response) => self.page('/', 'index', response, false, true));
```

__Arguments__:

- `/` a relative URL address
- `index` is a view name
- `response` is a model
- `cache` enables/disables caching
- `partial` - if `true` then can disable sitemap validation because partial pages aren't in the sitemap (it means e.g. banners, etc.)

Thank you!

**Comment by Wataru811** [comment]
Thank you so much for quick response! 

total.js is really great system. I'm very happy to learn it :))) , again thank you very much!
