### ISSUE TITLE
Cannot send emails

### ISSUE THREAD

**Issue by raisty** [totaljs/eshop#45]
I am using Sparkpost email provider and I don't have any success setup shop to work with this provider.
Maybe my settings in application are not correct.
Can you, please update me about email settings in documentation or how it setup properly?

Bottomline
In any case it is great application.
Working on AWS as well.

**Comment by petersirka** [comment]
Try to set configuration according to this settings:
<https://docs.totaljs.com/latest/en.html#pages~Troubleshooting~(smtp-settings-for-gmail-office-and-zoho)>

If won't be work then I need some SMTP access for testing.

**Comment by raisty** [comment]
I have following settings: 
`{ secure: true, port: 587, user: SMTP_Injection, password: diego, timeout: 180000 }`

Sparkpost says:
You need to connect using TLS (STARTTLS)

Maybe this is my issue.

**Comment by petersirka** [comment]
Try use the config below for sending emails:

```json
{"port":587,"secure":false,"user":"ENTER_YOUR_EMAIL","password":"ENTER_YOUR_PASSWORD","tls":{"ciphers":"SSLv3"}}
```

**Comment by raisty** [comment]
Seems, working now. Thank you
