### ISSUE TITLE
No Authorization For This API "http://localhost:8000/api/users/settings/"

### ISSUE THREAD

**Issue by MohammedGomaaS** [totaljs/eshop#46]
-With this API "http://localhost:8000/api/users/settings/", I can update the data for any user.
-I tested it with this header
*Request Header
--Method:put.
--Content-Type:application/json.
--Body:{
	"firstname":"abc",
	"lastname":"llll",
"name":"abc llll",
"email":"sa@sa.com",
"password":"1234567"

}*

**Comment by petersirka** [comment]
And what's the response?

**Comment by MohammedGomaaS** [comment]
The response.
{
    "success": true,
    "value": 1
}

**Comment by petersirka** [comment]
Do you use classic or premium version?

**Comment by MohammedGomaaS** [comment]
The steps that i took 
1-I downloaded a version from this link "https://my.totaljs.com/".
2-from postman,i created new user from this API "http://0.0.0.0:8000/api/users/create/".
*Request Header
--Method:post.
--Content-Type:application/json.
--Body:{"email":"khaled@gmail.com","firstname":"Khaled","gender":"male","isterms":true,"lastname":"Gomaa","password":"123456789","passwordreply":"","phone":"+201150441989"}
3-from postman,i updated the user from this API "http://0.0.0.0:8000/api/users/settings/".
*Request Header
--Method:put.
--Content-Type:application/json.
--Body:
{"email":"khaled@gmail.com","firstname":"Khaled","lastname":"Gomaa","password":"123456"}
---------------
response{
    "success": true,
    "value": 1
}

**Comment by petersirka** [comment]
Hmm, I have tested it now via Paw app and it works correcly:

![image](https://user-images.githubusercontent.com/2414252/34353463-9887a0ac-ea28-11e7-9ed2-099e45458b77.png)

Are you sure the postman doesn't send any cookie?

**Comment by MohammedGomaaS** [comment]
After tracking this bug.
I think this api(http://0.0.0.0:8000/api/users/settings/) updates the last document of the "users" collection
that created with this api"http://0.0.0.0:8000/api/users/create/".

**Comment by petersirka** [comment]
Yes, it's true:

- `/api/users/create/` creates a user and it logs him automatically (which creates a cookie)
- `/api/users/settings/` changes the user profile according to the `cookie`

So try to remove auth cookie and try to change profile data.

**Comment by MohammedGomaaS** [comment]
I doesn't use auth cookie when i send the request using postman.
 
![api](https://user-images.githubusercontent.com/16269515/34357180-7e33076c-ea4d-11e7-8830-65c11501103b.png)

**Comment by petersirka** [comment]
Can you export your postman requests?

**Comment by MohammedGomaaS** [comment]
[create and update user.postman_collection.json.tar.gz](https://github.com/totaljs/eshop/files/1587449/create.and.update.user.postman_collection.json.tar.gz)

**Comment by petersirka** [comment]
It works correctly. As I wrote:

- `/api/users/create/` creates a new user and cookie
- `/api/users/settings/` modifies a user profile according to the cookie

Postman automatically uses cookies which `create` endpoint creates. If you remove auth cookie then you get `401: Unauthorized`.

**Comment by MohammedGomaaS** [comment]
I think you are right because when i do this by JavaScript it responds with html body "No Authorization".

Sorry,
Thanks.
