### ISSUE TITLE
problem with nosql tmp

### ISSUE THREAD

**Issue by b3hz4d** [totaljs/eshop#49]
Hi,
I have really bad problem with this error:

have error: Error: ENOENT: no such file or directory, rename '/www/www/eshop/databases/users.nosql-tmp' -> '/www/www/eshop/databases/users.nosql'

**Comment by petersirka** [comment]
Which version of Total.js do you use? Do you use cluster?

**Comment by b3hz4d** [comment]
2.9.4

**Comment by petersirka** [comment]
__Do you use cluster?__ Please describe me where/when/under what conditions this problem has been created?

**Comment by b3hz4d** [comment]
No I don't user cluster.
I get this error when I wanna insert data into nosql db.

**Comment by b3hz4d** [comment]
And I'm using superadmin for it

**Comment by b3hz4d** [comment]
I found more information
Whenever I update db with large data with nosql modify method this error shows up
Maybe db become so large and it cant search for specific id using where method?
