### ISSUE TITLE
eshop >= 8.0.0 with mongodb instead of NoSQL Embedded ?

### ISSUE THREAD

**Issue by smonv** [totaljs/eshop#50]
Anyone can provide some examples integrate eshop with mongodb ? I tried with sqlagent but it wasn't working.

**Comment by petersirka** [comment]
Hi,  it doesn't support MongoDB. Why do you want to use MongoDB? How many products do you expect?

**Comment by smonv** [comment]
I got some exists system I want to integrate with. So even with `sqlagent`, I can't change models code to support MongoDB right ?

**Comment by petersirka** [comment]
No, eshop is optimized for Total.js NoSQL embedded database only... You can change the models but it takes much time....

**Comment by smonv** [comment]
Thank you for answer.
