### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by ryanaltair** [totaljs/eshop#52]
anyone know how to add translation?

I am willing to join TRANSLATION

**Comment by petersirka** [comment]
Hi @ryanaltair,
- do you have a resource file with translated text?
- __if no__ then follow <https://docs.totaljs.com/latest/en.html#pages~Localization~(create-resource)>
- __if yes__ then copy your file according to the path `youreshop/resources/default.resource`

**Comment by ryanaltair** [comment]
thanks
