### ISSUE TITLE
can i change logo , fonts? 

### ISSUE THREAD

**Issue by eddiezzy1** [totaljs/eshop#53]
how can i change font logo i can't find file to edit

**Comment by eddiezzy1** [comment]
[https://imgur.com/a/odmfr9p](url)
update : i change font in css and layout.html 
and stuck at load see pic in url

**Comment by petersirka** [comment]
Just update a source-code: `layout.html`.

**Comment by eddiezzy1** [comment]
@petersirka thanks for reply sir

this code from layout.html 

`<!DOCTYPE html>
<html>
<head>        <meta charset="utf-8" />        <meta http-equiv="X-UA-Compatible" content="IE=10" />        <meta name="format-detection" content="telephone=no" />        <meta name="viewport" content="width=device-width, initial-scale=1, user-scala$        <meta name="robots" content="all,follow" />        <link rel="styesheet" href="//cdn.componentator.com/spa.min@14.css" >         <link href="https://fonts.googleapis.com/css?family=Kanit:300,400,500,600,700$        <lnk rel="stylesheet" href="@{global.css}" />        <script src="//cdn.componentator.com/spa.min@14.js"></script>        @{import('meta', 'head', 'default.css', 'default.js', 'favicon.ico')}        <script>var LOGGED = +'@{if user}1@{else}0@{fi}';</script>
</head>
<body data-jc="exec,binder,modificator">        <br />        <div data-jc="loading" class="ui-loading@{if !repository.loading} hidden@{fi}"$        <div data-jc="shoppingcart" data-jc-path="shoppingcart" data-jc-config="discou$        <div data-jc="message" data-jc-config="button:@(Close)"></div>        <div data-jc="autocomplete"></div>        <div class="container">                <div class="relative">                        <div class="account">                                @{if user}                                        <a href="@{sitemap_url('account')}" class="b">$                                        <a href="@{sitemap_url('settings')}"><i class=$                                        <a href="@{sitemap_url('logoff')}"><i class="f$                                @{else}
                                        <a href="@{sitemap_url('account')}"><i class="$                                @{fi}                        </div>                </div
`
i just change in line googleapi to font i want to use
and edit default.css change font from source san pro to kanit font
 here is code from default.css
`/*auto*/
html,body { margin: 0; padding: 0; }
body { background-color: #F0F0F0; }
.CMS_hidden { display: none; }
.wp { padding-left: 20px; padding-right: 20px; }
.wpi {}
.wm { margin-bottom: 20px; }
.wmi { margin-bottom: 20px; }
.wnowrap { text-overflow: ellipsis; white-space: nowrap; overflow: hidden; }
.right { text-align: right; }
.center { text-align: center; }
header { height: 80px; }
header nav { display: block; margin-bottom: 10px; }
header nav a { font-size: 14px; font-family: 'Kanit', san-serif; margin-left: 20px; te$header nav a:hover { text-decoration: none; color: black; }
header nav a:first-child { margin-left: 0; }
header nav .fa { margin-right: 5px; }
.relative { position: relative; }
.account { position: absolute; font-size: 12px; border-radius: 3px; margin: 3px 0 0 0;$.account .fa { margin-right: 5px; }
.account a { margin-left: 10px; border-left: 1px solid #D0D0D0; padding-left: 10px; }
.account a:first-child { border-left: 0; margin-left: 0; padding-left: 0; }
.categories { background-color: white; border-radius: 3px; box-shadow: 0 10px 20px rgb$.categories button { width: 120px; margin: 0 auto; display: none; background-color: wh$                                  `

thanks again bro @petersirka

**Comment by eddiezzy1** [comment]
> Just update a source-code: `layout.html`.

sorry im new here i confused to comment

**Comment by petersirka** [comment]
__Recommendation__:
- you need to learn Total.js framework first
- then you can modify a source-code

__Here is a logo:__
https://github.com/totaljs/eshop/blob/master/themes/default/views/layout.html#L40

For more info use https://messenger.totaljs.com
