### ISSUE TITLE
Please add support for other databases

### ISSUE THREAD

**Issue by ANTEVETY** [totaljs/eshop#54]
I like all your products. I would like to go with the store in production, but your database does not have enough replication. It would be great to see the couchbase or cockrouchdb(postgresql), perhaps through dmbs. Maybe in the form of premium packages?

**Comment by petersirka** [comment]
Hi @ANTEVETY,
thank you, but this is not possible because entire eshop is optimized for NoSQL embedded database and new version will be optimized too. I have had a plan for advanced eshop built on PostgreSQL or MySQL but nobody who should paid for it :-D

**Comment by ANTEVETY** [comment]
If I correctly translated it: "I have had a plan for advanced eshop built on PostgreSQL or MySQL but nobody who should paid for it :-D"... How much money is required to collect in order for an update to support postgres or mongo, couchbase... in the Eshop? Maybe a spoiler on the main page of the site for donations.

**Comment by ANTEVETY** [comment]
I took advantage of free time and wrote on the site a small [overview](https://habr.com/post/426839/) of the main features of the Total. I hope the russian community will somehow help development, and for example it motivates you to supplement and inject to Total products other databases;) Your marketplace works just hidden from passersby... in order to participate I need to become a premium?

**Comment by petersirka** [comment]
Thank you! I really appreciate it. I will think about it, maybe I will a free time on Christmas :-D
