### ISSUE TITLE
How to place Currency before amount?

### ISSUE THREAD

**Issue by omaisali** [totaljs/eshop#60]
Hi, 

In our country we have Currency before amount. From where i can change placement of currency?

**Comment by petersirka** [comment]
Hi, you can change this behaviour here:
https://github.com/totaljs/eshop/blob/master/models/settings.js#L142

**Comment by omaisali** [comment]
> Hi, you can change this behaviour here:
> https://github.com/totaljs/eshop/blob/master/models/settings.js#L142

Thank you so much, Made my day. 

I changed to this 

`default:
					settings.currency_entity = F.global.config.currency + '{0} ';`

**Comment by omaisali** [comment]
@petersirka one quick question if you can help, how i can disable paypal?
